language: python

env:
  global:
      - PATH=/usr/lib/ccache:$PATH

cache: ccache

os:
  - linux

sudo: false

matrix:
  include:
    - env: CUDA=yes
      python: "3.6"
      addons:
        apt:
          packages:
            - nvidia-common
            - nvidia-cuda-toolkit
            - nvidia-cuda-dev
  exclude:
    - os: linux


# See astra-toolbox
before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

install:
  - conda install python=$TRAVIS_PYTHON_VERSION six numpy scipy cython
  - conda info -a
  - mkdir build; cd build; cmake ..
  - cd build; make -j 4

script:
  - python -c "import b3d"
